### PR TITLE
Added keys function to get keys matching a pattern

### PR DESCRIPTION
**Pull request by U-Prince**

### CODE REVIEW

**Comment by U-Prince** [comment]
In order to evict multiple keys synchronously starting with the same prefix id, a mechanism is required to fetch all keys matching the prefix and then delete all of them.

**Review by jsumners — CHANGES_REQUESTED** [review]
Please update the documentation to describe this method.

**Review by jsumners — APPROVED** [review]
LGTM

I'll do a release when I am able.

**Comment by U-Prince** [comment]
> LGTM
> 
> I'll do a release when I am able.

It would be helpful if the release is done at the earliest as I am using it in a project. Thank you

**Comment by jsumners** [comment]
https://github.com/jsumners/abstract-cache-redis/releases/tag/v1.1.0

**Pull request merged**
